name: "Oculex-alpha"
version: "0.1.24"
slug: "oculex"
description: "An OCR Stream Aggregator that ingests video streams (e.g. RTSP), extracts text via OCR, and provides unified output. Designed to integrate nicely with Home Assistant for automations, monitoring, and logging."
url: "https://github.com/JoelHer/Oculex"
startup: services
boot: auto
ports:
  5000/tcp: 5000

options:
  rtsp_url: "rtsp://user:password@ip:port/location" 
  debug_mode: false
  ocr_interval: 3600 # Interval in seconds for periodic OCR reading
  liters_per_hour: 10
schema:
  debug_mode: "bool"


arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386


ingress: false

panel_admin: true
webui: http://[HOST]:[PORT:5000]/
